INSERT INTO Localisation (description) VALUES 
('Allée 1-A - Chemins de câbles / Goulottes'),
('Allée 1-B - VR / Portes sectionnelles'),
('Allée 1-C - Fermetures / Fermes portes'),
('Allée 1-D - Menuiserie / Quincaillerie / Gâches électriques'),
('Allée 1-E - Barres palpeuses / Manivelles'),
('Allée 2-A - Barres antipaniques / Canons / Divers'),
('Allée 2-B - Clim'),
('Allée 2-C - Plomberie'),
('Allée 2-D - Plomberie'),
('Allée 2-E - Plomberie / Pompes'),
('Allée 2-F - Plomberie / Matériel plafond'),
('Allée 3-A - Eclairages'),
('Allée 3-B - Eclairages'),
('Allée 3-C - Eclairages'),
('Allée 3-D - Eclairages'),
('Allée 3-E - Extincteurs / Incendie'),
('Allée 3-F - Extincteurs / Incendie'),
('Allée 4-A - Extincteurs / Incendie'),
('Allée 4-B - Extincteurs / Incendie'),
('Allée 4-C - Electricité'),
('Allée 4-D - Electricité'),
('Allée 4-E - Electricité'),
('Allée 4-F - Electricité'),
('Allée 4-G - Electricité'),
('Allée 5-A - DM / Détecteurs / Centrales'),
('Allée 5-B - Incendie BAES'),
('Allée 5-C - Informatique / Son / Vidéo / TV'),
('Allée 5-D - VMC'),
('Allée 5-E - Interphone'),
('Allée 5-F - Incendie Siemens'),
('Allée 5-G - Incendie DM / Détecteurs / Centrales'),
('Allée 5-H - Incendie DM / Détecteurs / Centrales'),
('Allée 5-I - Incendie ventouses'),
('Allée 6-A - Contrôle d''accès / Intrusion'),
('Allée 6-B - Intrusion'),
('Allée 6-C - Contrôle d''accès / Intrusion'),
('Allée 6-D - AES / Batterie'),
('Allée 6-E - Crémaillères'),
('Allée 6-F - Automatisme'),
('Allée 6-G - Automatisme'),
('Allée 6-H - Automatisme'),
('Allée 7-A - Câbles'),
('Allée 7-B - Câbles'),
('Allée 7-C'),
('Allée 7-D'),
('Allée 7-E'),
('Allée 7-F - Fibre'),
('Allée 7-G - Goulotte clim');
